[phases.setup]
nixPkgs = ["python311", "gcc", "libmariadb-dev", "pkg-config"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && python railway_start.py && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:create_app()"
