[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python railway_start.py && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:create_app()"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
FLASK_ENV = "production"
